(deftheme root
  "Created 2019-04-09.")

(custom-theme-set-faces
 'root
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#c5c8c6" :background "#1d1f21" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#cc6666"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#81a2be"))))
 '(highlight ((t (:inverse-video nil :foreground "#e1e1e0" :background "#282a2e"))))
 '(region ((t (:inverse-video nil :foreground "#e1e1e0" :background "#373b41"))))
 '(shadow ((t (:foreground "#969896"))))
 '(secondary-selection ((t (:background "#282a2e"))))
 '(trailing-whitespace ((t (:underline nil :background "#ff4242" :inherit (whitespace-trailing)))))
 '(font-lock-builtin-face ((t (:foreground "#b294bb"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#969896"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#969896"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#81a2be"))))
 '(font-lock-doc-face ((t (:slant oblique :foreground "#b294bb"))))
 '(font-lock-function-name-face ((t (:height 1.1 :weight bold :foreground "#de935f"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#b5bd68"))))
 '(font-lock-negation-char-face ((t (:foreground "#81a2be"))))
 '(font-lock-preprocessor-face ((t (:slant italic :foreground "#b294bb"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#f0c674"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#b294bb"))))
 '(font-lock-string-face ((t (:foreground "#8abeb7"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#81a2be"))))
 '(font-lock-variable-name-face ((t (:weight bold :foreground "#f0c674"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#cc6666"))))
 '(button ((t (:weight bold :underline (:color foreground-color :style line) :box (:line-width 2 :color "grey" :style released-button) :foreground "black" :background "grey"))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#ed74cd"))))
 '(fringe ((t (:foreground "#969896" :background "#22a224a427a7"))))
 '(header-line ((t (:height 0.9 :box (:line-width -1 :color "grey20" :style released-button) :foreground "#8abeb7" :inherit (mode-line-inactive)))))
 '(tooltip ((t (:inverse-video t :foreground "#f0c674" :background "#1d1f21"))))
 '(mode-line ((t (:height 0.9 :weight normal :box (:line-width 1 :color "#373b41" :style nil) :foreground "#c5c8c6" :background "#373b41"))))
 '(mode-line-buffer-id ((t (:height 0.9 :weight bold :foreground "#b294bb"))))
 '(mode-line-emphasis ((t (:weight bold :slant italic :foreground "#c5c8c6"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#b294bb"))))
 '(mode-line-inactive ((t (:height 0.9 :weight normal :box (:line-width 1 :color nil :style nil) :foreground "#969896" :background "#282a2e" :inherit (mode-line)))))
 '(isearch ((t (:inverse-video t :foreground "#f0c674" :background "#1d1f21"))))
 '(isearch-fail ((t (:inverse-video t :background "#1d1f21" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#8abeb7" :background "#1d1f21"))))
 '(match ((t (:inverse-video t :foreground "#81a2be" :background "#1d1f21"))))
 '(next-error ((t (:background "blue3"))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2")))))

(provide-theme 'root)
